apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "microservice", "namespace": "", "kind": "DeploymentConfig"}]'
    name: microservice-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/avrdevops/git-usuarios.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: FiArdDBH
      type: Generic
